services:
  - type: web
    name: student-attendance-system
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn student_management_system.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: student_attendance_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true

databases:
  - name: student_attendance_db
    plan: free
    databaseName: student_attendance
    user: student_attendance_user
