services:
  - type: web
    name: student-attendance-system
    env: python
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn student_management_system.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: student-attendance-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true

databases:
  - name: student-attendance-db
    plan: free
