# Generated by Django 4.2.16 on 2025-08-04 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_alter_attendancereport_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['course_name'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['admin__first_name', 'admin__last_name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'ordering': ['course_id', 'subject_name'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student_management_app.courses'),
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='session_year_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student_management_app.sessionyearmodel'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.courses'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionyearmodel',
            unique_together={('session_start_year', 'session_end_year')},
        ),
        migrations.AlterUniqueTogether(
            name='subjects',
            unique_together={('subject_name', 'course_id')},
        ),
        migrations.AddConstraint(
            model_name='sessionyearmodel',
            constraint=models.CheckConstraint(check=models.Q(('session_end_year__gt', models.F('session_start_year'))), name='session_end_after_start'),
        ),
    ]
